name: notesapp_flutter
description: "Notes App with Flutter"
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.2
  cupertino_icons: ^1.0.2
  share_plus: ^7.2.1
  file_selector: ^1.0.3
  file_picker: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
